"""Fix is_current column type

Revision ID: 0b105d73a259
Revises: 7c6f95c34259
Create Date: 2025-11-08 00:47:01.096180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b105d73a259'
down_revision = '7c6f95c34259'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use USING clause to convert string to boolean
    op.execute("ALTER TABLE extracted_facts ALTER COLUMN is_current TYPE BOOLEAN USING is_current::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extracted_facts', 'is_current',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
