"""Add image fields to conversation partners

Revision ID: 00867659caf6
Revises: 0b105d73a259
Create Date: 2025-11-08 00:54:37.012432

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '00867659caf6'
down_revision = '0b105d73a259'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_partners', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('conversation_partners', sa.Column('image_embedding', Vector(512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_partners', 'image_embedding')
    op.drop_column('conversation_partners', 'image_url')
    # ### end Alembic commands ###
