"""Update vector dimensions to 4096

Revision ID: 67f74e9cc4a7
Revises: 00867659caf6
Create Date: 2025-11-08 01:00:18.201985

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '67f74e9cc4a7'
down_revision = '00867659caf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Clear existing embeddings before changing dimensions
    op.execute('UPDATE conversation_partners SET image_embedding = NULL')
    op.execute('UPDATE conversations SET embedding = NULL')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_partners', 'image_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=512),
               type_=pgvector.sqlalchemy.Vector(dim=4096),
               existing_nullable=True)
    op.alter_column('conversations', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=4096),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=4096),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=True)
    op.alter_column('conversation_partners', 'image_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=4096),
               type_=pgvector.sqlalchemy.Vector(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###
